# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20170610_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='profile',
            field=models.CharField(default='https://scontent-sit4-1.xx.fbcdn.net/v/t1.0-9/12247082_416775445188441_4548757330245763777_n.jpg?oh=96b70062c36d709e94e621b753ac7c3a&oe=599EA8D8', max_length=100),
            preserve_default=False,
        ),
    ]
