# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogs',
            name='profile',
            field=models.CharField(blank=True, default='https://cdn4.iconfinder.com/data/icons/rcons-user/32/boss_man-512.png', max_length=100, null=True),
        ),
    ]
