# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20170613_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='created',
        ),
    ]
