# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-18 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_remove_blogs_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='profile',
        ),
        migrations.AddField(
            model_name='blogs',
            name='uploadtime',
            field=models.TextField(default='nothing'),
        ),
    ]
