# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-18 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20170618_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='uploadtime',
            field=models.DateTimeField(default='nothing'),
        ),
    ]
