# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-18 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
