# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=models.TextField(),
        ),
    ]
