# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_blogs_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='tags',
        ),
    ]
