# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogs_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='profile',
            field=models.CharField(default=b'http://www.iconsdb.com/icons/preview/caribbean-blue/contacts-xxl.png', max_length=100),
        ),
    ]
