# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20170610_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='profile',
            field=models.CharField(blank=True, default=b'http://www.iconsdb.com/icons/preview/caribbean-blue/contacts-xxl.png', max_length=100, null=True),
        ),
    ]
